version: "2"
services:
    nginx_firstapp:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - "8080:80"
        volumes:
            - .:/src
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - flask
    redis:
        image: redis:2.8.19
        hostname: redis

    flask:
        build: .
        hostname: "${PROJECT_NAME}_flask"
        container_name: "${PROJECT_NAME}_flask"
        command: bash -c "flask run --host=0.0.0.0 --port=80"
        volumes:
            - .:/src
        expose:
            - "80"
        links:
            - postgresql:postgresql
            - redis:redis
        depends_on:
            - postgresql
            - redis
        environment:
            - C_FORCE_ROOT=true
            - FLASK_APP=server.py
            - FLASK_DEBUG=1

    postgresql:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"

    data:
        image: postgres:9.3
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
